package hash

// generated by hasher -type=Hash -file=hash.go; DO NOT EDIT, except for adding more constants to the list and rerun go generate

// uses github.com/tdewolff/hasher
//go:generate hasher -type=Hash -file=hash.go

// Hash defines perfect hashes for a predefined list of strings
type Hash uint32

// Unique hash definitions to be used instead of strings
const (
	Arccos  Hash = 0x1906 // arccos
	Arccosh Hash = 0x1907 // arccosh
	Arcsin  Hash = 0x6    // arcsin
	Arcsinh Hash = 0x7    // arcsinh
	Arctan  Hash = 0x706  // arctan
	Arctanh Hash = 0x707  // arctanh
	Cbrt    Hash = 0xe04  // cbrt
	Cos     Hash = 0x1c03 // cos
	Cosh    Hash = 0x1c04 // cosh
	Erf     Hash = 0x2303 // erf
	Exp     Hash = 0x1203 // exp
	Gamma   Hash = 0x1505 // gamma
	Inverf  Hash = 0x2006 // inverf
	Ln      Hash = 0x2602 // ln
	Log     Hash = 0x2803 // log
	Log10   Hash = 0x2805 // log10
	Log2    Hash = 0x2d04 // log2
	Sin     Hash = 0x303  // sin
	Sinh    Hash = 0x304  // sinh
	Sqrt    Hash = 0x3104 // sqrt
	Tan     Hash = 0xa03  // tan
	Tanh    Hash = 0xa04  // tanh
)

// String returns the hash' name.
func (i Hash) String() string {
	start := uint32(i >> 8)
	n := uint32(i & 0xff)
	if start+n > uint32(len(_Hash_text)) {
		return ""
	}
	return _Hash_text[start : start+n]
}

// ToHash returns the hash whose name is s. It returns zero if there is no
// such hash. It is case sensitive.
func ToHash(s []byte) Hash {
	if len(s) == 0 || len(s) > _Hash_maxLen {
		return 0
	}
	h := uint32(_Hash_hash0)
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	if i := _Hash_table[h&uint32(len(_Hash_table)-1)]; int(i&0xff) == len(s) {
		t := _Hash_text[i>>8 : i>>8+i&0xff]
		for i := 0; i < len(s); i++ {
			if t[i] != s[i] {
				goto NEXT
			}
		}
		return i
	}
NEXT:
	if i := _Hash_table[(h>>16)&uint32(len(_Hash_table)-1)]; int(i&0xff) == len(s) {
		t := _Hash_text[i>>8 : i>>8+i&0xff]
		for i := 0; i < len(s); i++ {
			if t[i] != s[i] {
				return 0
			}
		}
		return i
	}
	return 0
}

const _Hash_hash0 = 0xf0c5341e
const _Hash_maxLen = 7
const _Hash_text = "arcsinharctanhcbrtexpgammarccoshinverflnlog10log2sqrt"

var _Hash_table = [1 << 5]Hash{
	0x0:  0x7,    // arcsinh
	0x1:  0x1c04, // cosh
	0x2:  0x706,  // arctan
	0x3:  0xa04,  // tanh
	0x4:  0x2602, // ln
	0x5:  0x1203, // exp
	0x7:  0x1505, // gamma
	0x8:  0x6,    // arcsin
	0x9:  0x2805, // log10
	0xd:  0x1906, // arccos
	0xe:  0x2006, // inverf
	0xf:  0x304,  // sinh
	0x11: 0x1c03, // cos
	0x12: 0x2d04, // log2
	0x14: 0x2803, // log
	0x16: 0x2303, // erf
	0x19: 0xa03,  // tan
	0x1b: 0x303,  // sin
	0x1c: 0x3104, // sqrt
	0x1d: 0x707,  // arctanh
	0x1e: 0xe04,  // cbrt
	0x1f: 0x1907, // arccosh
}
